server:
  port: 8082
spring:
  application:
    name: service-objcat-1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
